version: '3'

services:
  node:
    build:
      context: ./node
    container_name: node
    image: anizairl/nodedes:prod
    entrypoint: docker-entrypoint.sh
    command: node index.js
    expose:
      - 3000
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
    tty: true
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network
  
  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    image: anizairl/nginxdes:prod
    container_name: nginx
    networks:
      - node-network
    ports:
      - 8080:80
    depends_on:
      - node

networks:
  node-network:
    driver: bridge

